# Generated by Django 6.0.1 on 2026-01-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='modified',
            field=models.BooleanField(default=False, help_text='True if item was returned or modified'),
        ),
        migrations.CreateModel(
            name='StockAdditionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('modified', models.BooleanField(default=False, help_text='True if stock addition was returned or modified')),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.userprofile')),
                ('cheese_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.cheeseproduct')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_returned', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.saleitem')),
                ('stock_addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.stockadditionhistory')),
            ],
            options={
                'ordering': ['-date_returned'],
            },
        ),
    ]
