# Generated by Django 6.0.1 on 2026-01-21 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_saleitem_modified_stockadditionhistory_return'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('cash', 'Cash'), ('online', 'Online')], max_length=10)),
                ('bank', models.CharField(blank=True, help_text='Required if mode is online', max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.client')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
