# Generated by Django 6.0.1 on 2026-01-18 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0002_remove_client_email_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cheeseproduct',
            old_name='available_quantity_kg',
            new_name='available_quantity_packets',
        ),
        migrations.RenameField(
            model_name='cheeseproduct',
            old_name='purchase_price_per_kg',
            new_name='purchase_price_per_packet',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='profit_per_kg',
            new_name='profit_per_packet',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='quantity_kg',
            new_name='quantity_packets',
        ),
        migrations.RenameField(
            model_name='saleitem',
            old_name='selling_price_per_kg',
            new_name='selling_price_per_packet',
        ),
    ]
