# Generated by Django 4.2.25 on 2026-03-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0003_payment'),
        ('distribution', '0003_sale_amount_paid_sale_payment_date_and_more'),
    ]

    operations = [
    ]
