# Generated by Django 4.2.25 on 2026-03-19 17:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution', '0004_merge_20260319_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('id_card_number', models.CharField(max_length=50)),
                ('joining_date', models.DateField()),
                ('route', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('bike_maintenance', 'Bike Maintenance'), ('fuel', 'Fuel'), ('food', 'Food'), ('salary', 'Salary'), ('note', 'Note')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set 0 for note-only expenses.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('note', models.TextField(blank=True)),
                ('expense_date', models.DateField(default=django.utils.timezone.localdate)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.deliveryemployee')),
            ],
            options={
                'ordering': ['-expense_date', '-id'],
            },
        ),
    ]
