# Generated by Django 4.2.25 on 2026-03-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0005_deliveryemployee_deliveryexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryemployee',
            name='route_from',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryemployee',
            name='route_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
