# Generated by Django 4.2.29 on 2026-03-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0006_deliveryemployee_route_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
