# Generated by Django 4.2.29 on 2026-03-25 16:12

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0007_alter_manufacturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryexpense',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='deliveryexpense',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.deliveryemployee'),
        ),
        migrations.AlterField(
            model_name='deliveryexpense',
            name='expense_type',
            field=models.CharField(choices=[('bike_maintenance', 'Bike Maintenance'), ('fuel', 'Fuel'), ('food', 'Food'), ('salary', 'Salary'), ('general', 'General')], max_length=30),
        ),
    ]
