# Generated by Django 4.2.29 on 2026-03-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0008_alter_deliveryexpense_amount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity_time', models.DateTimeField(auto_now=True)),
                ('last_activity_description', models.CharField(default='', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Activity',
            },
        ),
    ]
