# Generated by Django 6.0.1 on 2026-03-30 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0010_remove_invoide_payment_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='return',
            name='stock_addition',
        ),
        migrations.RemoveField(
            model_name='stockadditionhistory',
            name='cheese_product',
        ),
        migrations.RemoveField(
            model_name='stockadditionhistory',
            name='quantity_packets',
        ),
        migrations.AddField(
            model_name='stockadditionhistory',
            name='fully_returned',
            field=models.BooleanField(default=False, help_text='True if all items were fully returned'),
        ),
        migrations.AlterField(
            model_name='stockadditionhistory',
            name='modified',
            field=models.BooleanField(default=False, help_text='True if any item was returned or modified'),
        ),
        migrations.CreateModel(
            name='StockAdditionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_packets', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_returned', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cheese_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.cheeseproduct')),
                ('stock_addition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution.stockadditionhistory')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='return',
            name='stock_addition_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.stockadditionitem'),
        ),
    ]
