# Generated by Django 6.0.1 on 2026-03-30 15:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0011_remove_return_stock_addition_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockadditionhistory',
            options={'ordering': ['-date_last_updated']},
        ),
        migrations.RemoveField(
            model_name='return',
            name='stock_addition_item',
        ),
        migrations.RemoveField(
            model_name='stockadditionhistory',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='stockadditionhistory',
            name='fully_returned',
        ),
        migrations.RemoveField(
            model_name='stockadditionhistory',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='stockadditionitem',
            name='quantity_returned',
        ),
        migrations.AddField(
            model_name='return',
            name='stock_addition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.stockadditionhistory'),
        ),
        migrations.AddField(
            model_name='stockadditionhistory',
            name='date_last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stockadditionhistory',
            name='operation_type',
            field=models.CharField(choices=[('add', 'Add Stock'), ('remove', 'Remove Stock'), ('price_change', 'Price Change')], default='add', max_length=20),
        ),
        migrations.AddField(
            model_name='stockadditionitem',
            name='new_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockadditionitem',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stockadditionitem',
            name='quantity_packets',
            field=models.IntegerField(),
        ),
    ]
