# Generated by Django 4.2.29 on 2026-04-03 10:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0012_alter_stockadditionhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='previous_debt',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Initial debt brought forward from before system implementation', max_digits=10),
        ),
    ]
