# Generated by Django 4.2.29 on 2026-04-03 10:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0013_add_previous_debt_to_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='quantity_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Quantity that has been returned', max_digits=10),
        ),
    ]
