# Generated by Django 4.2.29 on 2026-04-03 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0014_add_quantity_returned_to_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheeseproduct',
            name='available_quantity_packets',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
