# Generated by Django 4.2.29 on 2026-04-03 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0015_alter_cheeseproduct_available_quantity_packets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='address',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='contact_info',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
