# Generated by Django 4.2.29 on 2026-04-03 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0016_alter_client_address_alter_client_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='quantity_packets',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity_packets',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity_returned',
            field=models.IntegerField(default=0, help_text='Quantity that has been returned'),
        ),
    ]
