# Generated by Django 4.2.29 on 2026-04-23 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0021_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cheeseproduct',
            name='product_manufacturer_idx',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='client_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_client_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='payment_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_client_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='sale',
            name='sale_client_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='saleitem_sale_idx',
        ),
        migrations.RemoveIndex(
            model_name='saleitem',
            name='saleitem_product_idx',
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
