# Generated by Django 4.2.29 on 2026-04-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0022_remove_cheeseproduct_product_manufacturer_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('return', 'Return Items'), ('quantity_add', 'Add Quantity'), ('price_change', 'Change Price'), ('item_add', 'Add New Item')], max_length=20)),
                ('quantity_change', models.IntegerField(blank=True, null=True)),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for the action (e.g., customer return reason)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.userprofile')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='distribution.sale')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='distribution.saleitem')),
                ('stock_addition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution.stockadditionhistory')),
            ],
            options={
                'verbose_name_plural': 'Sale Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
