# Generated by Django 4.2.29 on 2026-04-23 15:29

from django.db import migrations, models
import django.db.models.deletion


def migrate_returns_to_sale_actions(apps, schema_editor):
    Return = apps.get_model('distribution', 'Return')
    SaleAction = apps.get_model('distribution', 'SaleAction')

    for old_return in Return.objects.select_related('sale_item', 'stock_addition'):
        sale = old_return.sale_item.sale if old_return.sale_item_id else None
        quantity_change = -old_return.quantity_packets if old_return.sale_item_id else old_return.quantity_packets

        action = SaleAction.objects.create(
            sale=sale,
            sale_item=old_return.sale_item,
            stock_addition=old_return.stock_addition,
            action_type='return',
            quantity_change=quantity_change,
            reason=old_return.reason or '',
        )
        SaleAction.objects.filter(pk=action.pk).update(created_at=old_return.date_returned)


def noop_reverse(apps, schema_editor):
    return None


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0023_saleaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_sales', to='distribution.userprofile'),
        ),
        migrations.AlterField(
            model_name='saleaction',
            name='action_type',
            field=models.CharField(choices=[('return', 'Return Items'), ('quantity_add', 'Add Quantity'), ('price_change', 'Change Price'), ('item_add', 'Add New Item'), ('void', 'Void Sale')], max_length=20),
        ),
        migrations.AlterField(
            model_name='saleaction',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='distribution.sale'),
        ),
        migrations.RunPython(migrate_returns_to_sale_actions, noop_reverse),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
