# Generated by Django 4.2.29 on 2026-04-23 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0024_sale_is_voided_sale_void_reason_sale_voided_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleaction',
            name='new_sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='saleaction',
            name='old_sale_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='saleaction',
            name='action_type',
            field=models.CharField(choices=[('return', 'Return Items'), ('quantity_add', 'Add Quantity'), ('price_change', 'Change Price'), ('item_add', 'Add New Item'), ('date_change', 'Change Sale Date'), ('void', 'Void Sale')], max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('amount_change', 'Change Amount'), ('date_change', 'Change Payment Date'), ('mode_change', 'Change Payment Mode')], max_length=20)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_date', models.DateTimeField(blank=True, null=True)),
                ('new_date', models.DateTimeField(blank=True, null=True)),
                ('old_mode', models.CharField(blank=True, max_length=10)),
                ('new_mode', models.CharField(blank=True, max_length=10)),
                ('old_bank', models.CharField(blank=True, max_length=100)),
                ('new_bank', models.CharField(blank=True, max_length=100)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.userprofile')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='distribution.payment')),
            ],
            options={
                'verbose_name_plural': 'Payment Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
