# Generated by Django 4.2.29 on 2026-04-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0025_saleaction_new_sale_date_saleaction_old_sale_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_payments', to='distribution.userprofile'),
        ),
        migrations.AlterField(
            model_name='paymentaction',
            name='action_type',
            field=models.CharField(choices=[('amount_change', 'Change Amount'), ('date_change', 'Change Payment Date'), ('mode_change', 'Change Payment Mode'), ('void', 'Void Payment')], max_length=20),
        ),
    ]
