# Generated by Django 4.2.29 on 2026-04-23 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution', '0026_payment_is_voided_payment_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryexpense',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryexpense',
            name='void_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='deliveryexpense',
            name='voided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryexpense',
            name='voided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voided_expenses', to='distribution.userprofile'),
        ),
        migrations.CreateModel(
            name='ExpenseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('date_change', 'Change Expense Date'), ('type_change', 'Change Expense Type'), ('amount_change', 'Change Amount'), ('employee_change', 'Change Employee'), ('void', 'Void Expense')], max_length=20)),
                ('old_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField(blank=True, null=True)),
                ('old_type', models.CharField(blank=True, max_length=30)),
                ('new_type', models.CharField(blank=True, max_length=30)),
                ('old_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_employee_id', models.IntegerField(blank=True, null=True)),
                ('new_employee_id', models.IntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='distribution.userprofile')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='distribution.deliveryexpense')),
            ],
            options={
                'verbose_name_plural': 'Expense Actions',
                'ordering': ['-created_at'],
            },
        ),
    ]
